# Generated by Django 3.0.5 on 2020-06-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20200609_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='modify_date',
            field=models.DateTimeField(null=True),
        ),
    ]
