# Generated by Django 3.0.5 on 2020-06-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20200611_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
