# Generated by Django 3.0.5 on 2020-06-16 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0005_auto_20200611_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('initDate', models.DateField(auto_now_add=True)),
                ('endDate', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toDo', to='team.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=False)),
                ('description', models.TextField(blank=True, max_length=800)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('priority', models.CharField(max_length=10)),
                ('order', models.IntegerField()),
                ('toDo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.ToDo')),
            ],
            options={
                'index_together': {('toDo', 'order')},
            },
        ),
    ]
